<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

*   Identify duplicate values in the dataset.

*   Remove duplicate values from the dataset.

*   Identify missing values in the dataset.

*   Impute the missing values in the dataset.

*   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [200]:
import pandas as pd
import numpy as np

Load the dataset into a dataframe.

In [201]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")

## Finding duplicates

In this section you will identify duplicate values in the dataset.

Find how many duplicate rows exist in the dataframe.

In [202]:
# your code goes here
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [203]:
# your code goes here
df.duplicated(keep='first').sum()

154

In [204]:
df.drop_duplicates(keep='first',inplace=True)

Verify if duplicates were actually dropped.

In [205]:
# your code goes here
df.duplicated(keep='first').sum()

0

In [206]:
df.shape

(11398, 85)

In [207]:
df['EdLevel'].isna().sum().sum()

112

In [208]:
df['Country'].isna().sum().sum()

0

## Finding Missing values

Find the missing values for all columns.

In [209]:
df.isna().sum()

Respondent        0
MainBranch        0
Hobbyist          0
OpenSourcer       0
OpenSource       81
               ...
Sexuality       542
Ethnicity       675
Dependents      140
SurveyLength     19
SurveyEase       14
Length: 85, dtype: int64

In [210]:
df.isna().sum().sum()

30967

Find out how many rows are missing in the column 'WorkLoc'

In [211]:
# your code goes here
df['WorkLoc'].isna().sum()

32

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [212]:
# your code goes here
df['WorkLoc'].value_counts()

Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: WorkLoc, dtype: int64

Identify the value that is most frequent (majority) in the WorkLoc column.

In [213]:
#make a note of the majority value here, for future reference
WorkLoc_mode=df['WorkLoc'].mode()[0]
WorkLoc_mode

'Office'

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [214]:
# your code goes here
df['WorkLoc'].fillna(value=WorkLoc_mode,inplace=True)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [215]:
# your code goes here
df['WorkLoc'].isna().sum()

0

In [216]:
df['Employment'].mode()[0]

'Employed full-time'

In [217]:
df['UndergradMajor'].value_counts()

Computer science, computer engineering, or software engineering          6953
Information systems, information technology, or system administration     794
Another engineering discipline (ex. civil, electrical, mechanical)        759
Web development or web design                                             410
A natural science (ex. biology, chemistry, physics)                       403
Mathematics or statistics                                                 372
A business discipline (ex. accounting, finance, marketing)                244
A social science (ex. anthropology, psychology, political science)        210
A humanities discipline (ex. literature, history, philosophy)             207
Fine arts or performing arts (ex. graphic design, music, studio art)      161
I never declared a major                                                  124
A health science (ex. nursing, pharmacy, radiology)                        24
Name: UndergradMajor, dtype: int64

In [218]:
df['ConvertedComp'].describe()

count    1.058200e+04
mean     1.315967e+05
std      2.947865e+05
min      0.000000e+00
25%      2.686800e+04
50%      5.774500e+04
75%      1.000000e+05
max      2.000000e+06
Name: ConvertedComp, dtype: float64

In [219]:
df['ConvertedComp'].median()

57745.0

In [220]:
df['ConvertedComp'].mode()

0    2000000.0
Name: ConvertedComp, dtype: float64

In [221]:
df[['ConvertedComp']]

       ConvertedComp
0            61000.0
1            95179.0
2            90000.0
3           455352.0
4            65277.0
...              ...
11547       130000.0
11548        19880.0
11549       105000.0
11550        80371.0
11551            NaN

[11398 rows x 1 columns]

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq".

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [222]:
# your code goes here
df['CompFreq'].unique()

array(['Yearly', 'Monthly', 'Weekly', nan], dtype=object)

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [223]:
df[['CompTotal']]

       CompTotal
0        61000.0
1       138000.0
2        90000.0
3        29000.0
4        90000.0
...          ...
11547   130000.0
11548    74400.0
11549   105000.0
11550    80000.0
11551        NaN

[11398 rows x 1 columns]

In [224]:
# your code goes here

#normalized_annual_compensation_dictionary={1,12,52}

#df['NormalizedAnnualCompensation']=df['CompTotal'].apply(lambda x: normalized_annual_compensation_dictionary[x])

#column_base=df['CompTotal']
#column_input=df['CompFreq']

In [225]:
df['CompFreq'].unique()

array(['Yearly', 'Monthly', 'Weekly', nan], dtype=object)

In [226]:
df['CompFreq'].drop_duplicates(keep='first',inplace=True)

In [227]:
df['CompFreq'].value_counts()

Yearly     6073
Monthly    4788
Weekly      331
Name: CompFreq, dtype: int64

In [237]:
df['NormalizedAnnualCompensation'].median()

100000.0

In [228]:
df['NormalizedAnnualCompensation']=np.where(
    df['CompFreq'] == 'Yearly', df['CompTotal'], np.where(
    df['CompFreq'] == 'Monthly', df['CompTotal'] * 12, np.where(
    df['CompFreq'] == 'Weekly', df['CompTotal'] * 52, np.nan)))

In [229]:
df['CompFreq'].isna().sum()

206

In [230]:
df['CompTotal'].isna().sum()

809

In [231]:
df['NormalizedAnnualCompensation'].isna().sum()

815

In [232]:
df[['CompFreq','CompTotal','NormalizedAnnualCompensation']]

      CompFreq  CompTotal  NormalizedAnnualCompensation
0       Yearly    61000.0                       61000.0
1       Yearly   138000.0                      138000.0
2       Yearly    90000.0                       90000.0
3      Monthly    29000.0                      348000.0
4       Yearly    90000.0                       90000.0
...        ...        ...                           ...
11547   Yearly   130000.0                      130000.0
11548   Yearly    74400.0                       74400.0
11549   Yearly   105000.0                      105000.0
11550   Yearly    80000.0                       80000.0
11551      NaN        NaN                           NaN

[11398 rows x 3 columns]

In [233]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase,NormalizedAnnualCompensation
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy,61000.0
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult,138000.0
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy,90000.0
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult,348000.0
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy,90000.0

## Authors

Ramesh Sannareddy

Francesco Pio Crovella

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |
| 2022-05-07        | 0.1     | Francesco Pio Crovella | Created final version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).